/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package Visual;

import Programa.MainBNB;
import Programa.Particular;
import Programa.Reserva;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;
import java.util.stream.Collectors;

public class ComprobarReservaAdmin extends javax.swing.JPanel {

    private ArrayList<Reserva> reservas = new ArrayList<>(); //Referencia al ArrayList de personas de la clase JavaBNB
    private ListIterator<Reserva> li; //Iterador para recorrer el ArrayList en ambas direcciones
    private Reserva objreserva; //Referencia a un objeto de tipo cliente del ArrayList

    public ComprobarReservaAdmin() {
        initComponents();
        errorNoSig.setVisible(false);
        errorNoAnt.setVisible(false);
        fechareserva.setEditable(false);
        fechallegada.setEditable(false);
        fechasalida.setEditable(false);
        name.setEditable(false);
        preciototal.setEditable(false);
        consultarTodo();
    }

    public void update() {
        errorNoSig.setVisible(false);
        errorNoAnt.setVisible(false);
        consultarTodo();
    }

    private void consultarTodo() {
        try {
            errorNoSig.setVisible(false);
            errorNoAnt.setVisible(false);

            if (MainBNB.getClientes() != null) {
                // Limpiar la lista de reservas antes de añadir las nuevas
                reservas.clear();

                // flatMap convierte un Stream<Stream<T>> en un Stream<T>, en este caso para conseguir un stream solo de reservas 
                List<Reserva> nuevasReservas = MainBNB.getInmuebles().stream()
                        .flatMap(inmueble -> inmueble.getReservas().stream())
                        .collect(Collectors.toList());

                reservas.addAll(nuevasReservas);
                //System.out.println(nuevasReservas);

                li = reservas.listIterator();
                if (reservas.size() < 1) {
                    jButtonSig.setEnabled(false);
                    jButtonAnt.setEnabled(false);
                    limpiarCampos();
                    return;
                } else {
                    jButtonSig.setEnabled(true);
                    jButtonAnt.setEnabled(true);
                }

                if (li.hasNext()) {
                    objreserva = li.next();
                } else {
                    errorNoSig.setVisible(true);
                }
                if (objreserva != null) {
                    presenta();
                } else {
                    limpiarCampos();
                    errorNoSig.setVisible(true);
                }
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }

    private void limpiarCampos() {
        fechallegada.setText("");
        fechareserva.setText("");
        fechasalida.setText("");
        name.setText("");
        preciototal.setText("");
        dnilabel.setText("");
        inmueblelabel.setText("");
    }

    private void presenta() {
        DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        fechallegada.setText(objreserva.getFechaInicio().format(formatoCorto));
        fechareserva.setText(objreserva.getFechaReserva().format(formatoCorto));
        fechasalida.setText(objreserva.getFechaFin().format(formatoCorto));
        name.setText(objreserva.getParticular().getNombre());
        preciototal.setText(String.valueOf(objreserva.calcularPrecioTotal()) + "€");
        dnilabel.setText(objreserva.getParticular().getDni());
        inmueblelabel.setText(objreserva.getInmueble().getTitulo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraarriba1 = new javax.swing.JPanel();
        titleLabel1 = new javax.swing.JLabel();
        mainscr = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        feLabel = new javax.swing.JLabel();
        frLabel = new javax.swing.JLabel();
        fechallegada = new javax.swing.JTextField();
        fechareserva = new javax.swing.JTextField();
        dnilabel = new javax.swing.JLabel();
        fsLabel = new javax.swing.JLabel();
        fechasalida = new javax.swing.JTextField();
        nLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        pLabel = new javax.swing.JLabel();
        preciototal = new javax.swing.JTextField();
        inmueblelabel = new javax.swing.JTextField();
        jButtonAnt = new javax.swing.JButton();
        jButtonSig = new javax.swing.JButton();
        errorNoSig = new javax.swing.JLabel();
        errorNoAnt = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 250, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraarriba1.setBackground(new java.awt.Color(255, 153, 102));
        barraarriba1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        barraarriba1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        titleLabel1.setForeground(new java.awt.Color(255, 90, 95));
        titleLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/logopeque.png"))); // NOI18N
        barraarriba1.add(titleLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        mainscr.setBackground(new java.awt.Color(255, 102, 102));
        mainscr.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 18)); // NOI18N
        mainscr.setForeground(new java.awt.Color(255, 255, 255));
        mainscr.setText("Volver");
        mainscr.setBorderPainted(false);
        mainscr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainscr.setPreferredSize(new java.awt.Dimension(80, 30));
        mainscr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainscrActionPerformed(evt);
            }
        });
        barraarriba1.add(mainscr, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 90, 40));

        jPanel1.add(barraarriba1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 89));

        jPanel3.setBackground(new java.awt.Color(255, 236, 217));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 250, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setMinimumSize(new java.awt.Dimension(325, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(325, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        feLabel.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        feLabel.setText("Fecha de llegada:");
        jPanel2.add(feLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        frLabel.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        frLabel.setText("Fecha de reserva:");
        jPanel2.add(frLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        fechallegada.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jPanel2.add(fechallegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 168, -1));

        fechareserva.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jPanel2.add(fechareserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 168, -1));

        dnilabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 18)); // NOI18N
        dnilabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dnilabel.setText("DNI");
        jPanel2.add(dnilabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 17, 191, -1));

        fsLabel.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        fsLabel.setText("Fecha de salida:");
        jPanel2.add(fsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        fechasalida.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jPanel2.add(fechasalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 168, -1));

        nLabel.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        nLabel.setText("Nombre:");
        jPanel2.add(nLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        name.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 168, -1));

        pLabel.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        pLabel.setText("Precio final:");
        jPanel2.add(pLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 20));

        preciototal.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jPanel2.add(preciototal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 168, -1));

        inmueblelabel.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        inmueblelabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inmueblelabel.setText("Inmueble");
        jPanel2.add(inmueblelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 56, 288, 28));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, 300));

        jButtonAnt.setBackground(new java.awt.Color(255, 153, 102));
        jButtonAnt.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 18)); // NOI18N
        jButtonAnt.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnt.setText("Anterior");
        jButtonAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAntActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jButtonSig.setBackground(new java.awt.Color(255, 153, 102));
        jButtonSig.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 18)); // NOI18N
        jButtonSig.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSig.setText("Siguiente");
        jButtonSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSigActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        errorNoSig.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 18)); // NOI18N
        errorNoSig.setText("No hay otra reserva");
        jPanel3.add(errorNoSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        errorNoAnt.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 18)); // NOI18N
        errorNoAnt.setText("No hay otra reserva");
        jPanel3.add(errorNoAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 730, 450));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 703));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSigActionPerformed
        if (li.hasNext()) {
            objreserva = li.next();
            errorNoSig.setVisible(false);
            errorNoAnt.setVisible(false);
            presenta();

        } else {
            errorNoSig.setVisible(true);
        }
    }//GEN-LAST:event_jButtonSigActionPerformed

    private void jButtonAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAntActionPerformed
        if (li.hasPrevious()) {
            objreserva = li.previous();
            errorNoSig.setVisible(false);
            errorNoAnt.setVisible(false);
            presenta();

        } else {
            errorNoAnt.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAntActionPerformed

    private void mainscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainscrActionPerformed
        Aplicacion.cardLayout.show(Aplicacion.cards, "Pantalla adminscreen");
    }//GEN-LAST:event_mainscrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraarriba1;
    private javax.swing.JLabel dnilabel;
    private javax.swing.JLabel errorNoAnt;
    private javax.swing.JLabel errorNoSig;
    private javax.swing.JLabel feLabel;
    private javax.swing.JTextField fechallegada;
    private javax.swing.JTextField fechareserva;
    private javax.swing.JTextField fechasalida;
    private javax.swing.JLabel frLabel;
    private javax.swing.JLabel fsLabel;
    private javax.swing.JTextField inmueblelabel;
    private javax.swing.JButton jButtonAnt;
    private javax.swing.JButton jButtonSig;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton mainscr;
    private javax.swing.JLabel nLabel;
    private javax.swing.JTextField name;
    private javax.swing.JLabel pLabel;
    private javax.swing.JTextField preciototal;
    private javax.swing.JLabel titleLabel1;
    // End of variables declaration//GEN-END:variables
}
