/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package Visual;

import Programa.Host;
import Programa.Cliente;
import Programa.Inmueble;
import Programa.MainBNB;
import Programa.Particular;
import Programa.Reserva;
import Programa.Validate;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.ListIterator;
import javax.swing.JOptionPane;

/**
 * La clase AdminConsultarUser permite al administrador consultar y gestionar
 * los usuarios registrados en la aplicación.
 */
public class ComprobarUsuarioAdmin extends javax.swing.JPanel {

    private ArrayList<Cliente> clientesaux; // Referencia al ArrayList de personas de la clase JavaBNB
    private ListIterator<Cliente> li; // Iterador para recorrer el ArrayList en ambas direcciones
    private Cliente objcli; // Referencia a un objeto de tipo cliente del ArrayList

    /**
     * Crea un nuevo formulario AdminConsultarUser.
     */
    public ComprobarUsuarioAdmin() {
        initComponents();
        errorNextLabel.setVisible(false);
        errorPreviousLabel.setVisible(false);
        nameTextField.setEditable(false);
        dniTextField.setEditable(false);
        emailTextField.setEditable(false);
        passTextField.setEditable(false);
        tlfTextField.setEditable(false);
        consultarTodo();
    }

    /**
     * Actualiza la vista y los datos de los usuarios.
     */
    public void update() {
        errorNextLabel.setVisible(false);
        errorPreviousLabel.setVisible(false);
        consultarTodo();
    }

    /**
     * Consulta y carga todos los usuarios de JavaBNB en la lista local.
     */
    private void consultarTodo() {
        try {
            errorNextLabel.setVisible(false);
            errorPreviousLabel.setVisible(false);

            if (MainBNB.getClientes() != null) {
                clientesaux = MainBNB.getClientes();

                li = clientesaux.listIterator();
                if (clientesaux.size() < 1) {
                    nextButton.setEnabled(false);
                    previousButton.setEnabled(false);
                    deleteUserButton.setEnabled(false);
                    editUserButton.setEnabled(false);
                    return;
                } else {
                    nextButton.setEnabled(true);
                    previousButton.setEnabled(true);
                    deleteUserButton.setEnabled(true);
                    editUserButton.setEnabled(true);
                }

                if (li.hasNext()) {
                    objcli = li.next();
                } else {
                    errorNextLabel.setVisible(true);
                }
                if (objcli != null) {
                    presenta(objcli);
                } else {
                    errorNextLabel.setVisible(true);
                }
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }

    /**
     * Presenta los detalles del usuario en los campos de texto
     * correspondientes.
     *
     * @param per el usuario cuyos detalles se van a mostrar
     */
    private void presenta(Cliente per) {
        String tipo = per.getClass().getSimpleName();
        dniTextField.setText(objcli.getDni());
        nameTextField.setText(objcli.getNombre());
        emailTextField.setText(objcli.getCorreo());
        passTextField.setText(objcli.getpassw());
        tlfTextField.setText(objcli.getTelefono());
        if (tipo.equals("Anfitrion")) {
            typeLabel.setText(tipo);
        } else {
            typeLabel.setText(tipo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraarriba1 = new javax.swing.JPanel();
        logoButton = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dniLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        dniTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passTextField = new javax.swing.JTextField();
        tlfLabel = new javax.swing.JLabel();
        tlfTextField = new javax.swing.JTextField();
        deleteUserButton = new javax.swing.JButton();
        editUserButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        errorNextLabel = new javax.swing.JLabel();
        errorPreviousLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 236, 217));

        barraarriba1.setBackground(new java.awt.Color(255, 236, 217));
        barraarriba1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        barraarriba1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoButton.setBackground(new java.awt.Color(255, 153, 153));
        logoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airbnb logo - 100x100.png"))); // NOI18N
        logoButton.setBorderPainted(false);
        logoButton.setContentAreaFilled(false);
        logoButton.setDefaultCapable(false);
        logoButton.setFocusPainted(false);
        logoButton.setFocusable(false);
        logoButton.setRequestFocusEnabled(false);
        logoButton.setRolloverEnabled(false);
        logoButton.setVerifyInputWhenFocusTarget(false);
        logoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoButtonActionPerformed(evt);
            }
        });
        barraarriba1.add(logoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 5, 71, 75));

        logoLabel.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 90, 95));
        logoLabel.setText("JavaBNB");
        barraarriba1.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 36, -1, -1));

        returnButton.setBackground(new java.awt.Color(255, 153, 102));
        returnButton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        returnButton.setForeground(new java.awt.Color(255, 255, 255));
        returnButton.setText("Volver");
        returnButton.setBorderPainted(false);
        returnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnButton.setPreferredSize(new java.awt.Dimension(80, 30));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        barraarriba1.add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 104, 53));

        jPanel3.setBackground(new java.awt.Color(255, 236, 217));

        jPanel2.setBackground(new java.awt.Color(255, 250, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setMinimumSize(new java.awt.Dimension(325, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(325, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dniLabel.setText("DNI:");
        jPanel2.add(dniLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        nameLabel.setText("Nombre:");
        jPanel2.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel2.add(dniTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 208, -1));
        jPanel2.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 208, -1));

        typeLabel.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        typeLabel.setText("var1");
        jPanel2.add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 20, 120, -1));

        emailLabel.setText("Correo:");
        jPanel2.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 20));
        jPanel2.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 208, -1));

        passLabel.setText("Contraseña:");
        jPanel2.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));
        jPanel2.add(passTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 208, -1));

        tlfLabel.setText("Telefono:");
        jPanel2.add(tlfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));
        jPanel2.add(tlfTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 208, -1));

        deleteUserButton.setBackground(new java.awt.Color(255, 153, 102));
        deleteUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteUserButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteUserButton.setText("Eliminar usuario");
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });
        jPanel2.add(deleteUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        editUserButton.setBackground(new java.awt.Color(255, 153, 102));
        editUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editUserButton.setForeground(new java.awt.Color(255, 255, 255));
        editUserButton.setText("Editar usuario");
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });
        jPanel2.add(editUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        previousButton.setBackground(new java.awt.Color(255, 153, 102));
        previousButton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        previousButton.setForeground(new java.awt.Color(255, 255, 255));
        previousButton.setText("Anterior");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        nextButton.setBackground(new java.awt.Color(255, 153, 102));
        nextButton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setText("Siguiente");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        errorNextLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        errorNextLabel.setText("No hay otro usuario");

        errorPreviousLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        errorPreviousLabel.setText("No hay otro usuario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(previousButton)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(errorPreviousLabel)
                                .addGap(63, 63, 63)
                                .addComponent(nextButton))
                            .addComponent(errorNextLabel)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorNextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(errorPreviousLabel)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextButton)
                            .addComponent(previousButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraarriba1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(barraarriba1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void logoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        Aplicacion.cardLayout.show(Aplicacion.cards, "Pantalla adminscreen");
    }//GEN-LAST:event_returnButtonActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        if (objcli != null) {
            if (objcli instanceof Particular) {
                Particular particular = (Particular) objcli;
                MainBNB.eliminarParticular(objcli);

                //Tengo que eliminar las reservas asociadas a ese particuar
                ArrayList<Inmueble> inmuebles = MainBNB.getInmuebles();
                for (Inmueble i : inmuebles) {
                    ArrayList<Reserva> reservas = i.getReservas();
                    Iterator<Reserva> iterator = reservas.iterator();
                    while (iterator.hasNext()) {
                        Reserva reserva = iterator.next();
                        if (reserva.getParticular().getDni().equals(objcli.getDni())) {
                            iterator.remove();
                        }
                    }
                }

            } else if (objcli instanceof Host) {
                Host anfitrion = (Host) objcli;
                ArrayList<Inmueble> inmuebles = MainBNB.getInmuebles();

                MainBNB.eliminarAnfitrion(objcli);

                MainBNB.getInmuebles().removeAll(inmuebles);
            }

            try {
                // Eliminar el cliente de la lista
                li.remove();

                // Guardar los datos actualizados
                MainBNB.guardarDatos();

                // update las vistas
                Aplicacion.adminconsultarreservas.update();
                Aplicacion.admincheckbuildings.update();
                Aplicacion.adminconsultaruser.update();
            } catch (Exception e) {
                System.out.println("Está vacío, no se puede eliminar más");
            }

        }

    }//GEN-LAST:event_deleteUserButtonActionPerformed

    private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserButtonActionPerformed
        // Verificar el texto actual del botón
        if (editUserButton.getText().equals("Editar datos")) {
            // Si el botón está en modo "Editar datos"
            // Establecer los campos de texto como editables
            emailTextField.setEditable(true);
            passTextField.setEditable(true);
            tlfTextField.setEditable(true);

            // Cambiar el texto del botón a "Aceptar"
            editUserButton.setText("Aceptar");
        } else {
            // Si el botón está en modo "Aceptar"
            // Establecer los campos de texto como no editables
            emailTextField.setEditable(false);
            passTextField.setEditable(false);
            tlfTextField.setEditable(false);

            // Cambiar el texto del botón a "Editar datos"
            editUserButton.setText("Editar datos");

            // Verificar la validez de los datos ingresados
            String email = emailTextField.getText();
            String password = passTextField.getText();
            String telefono = tlfTextField.getText();

            boolean datosValidos = true;

            // Verificar el correo electrónico
            if (!Validate.validarEmail(email)) {
                JOptionPane.showMessageDialog(this, "El email introducido no es válido.", "Email inválido", JOptionPane.WARNING_MESSAGE);
                emailTextField.setText("");
                datosValidos = false;
            } // Verificar la contraseña
            else if (!Validate.validarContraseña(password)) {
                JOptionPane.showMessageDialog(this, "La contraseña introducida no es válida. \n Revise los requisitos.", "Contraseña inválida", JOptionPane.WARNING_MESSAGE);
                passTextField.setText("");
                datosValidos = false;
            } // Verificar el teléfono
            else if (!Validate.validarTelefono(telefono)) {
                JOptionPane.showMessageDialog(this, "El teléfono introducido no es válido. \n Debe empezar por 6/7/9 y contener 9 números.", "Teléfono inválido", JOptionPane.WARNING_MESSAGE);
                tlfTextField.setText("");
                datosValidos = false;

            }

            // Si todos los datos son válidos, guardar los cambios
            if (datosValidos) {
                objcli.setCorreo(email);
                objcli.setTelefono(telefono);
                objcli.setpassw(password);

                editUserButton.setText("Editar datos");

                System.out.println(objcli);
            } else {
            }
        }
    }//GEN-LAST:event_editUserButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        if (li.hasPrevious()) {
            objcli = li.previous();
            errorNextLabel.setVisible(false);
            errorPreviousLabel.setVisible(false);
            presenta(objcli);

        } else {
            errorPreviousLabel.setVisible(true);
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (li.hasNext()) {
            objcli = li.next();
            errorNextLabel.setVisible(false);
            errorPreviousLabel.setVisible(false);
            presenta(objcli);

        } else {
            errorNextLabel.setVisible(true);
        }
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraarriba1;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JButton editUserButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel errorNextLabel;
    private javax.swing.JLabel errorPreviousLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logoButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField passTextField;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel tlfLabel;
    private javax.swing.JTextField tlfTextField;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
