/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package Visual;

/**
 *
 * @author javie
 */
public class PerfilCliente extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer PerfilCliente
     */
    public PerfilCliente() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        uppermenu = new javax.swing.JPanel();
        appname = new javax.swing.JLabel();
        logo = new javax.swing.JButton();
        logo1 = new javax.swing.JButton();
        mainscr = new javax.swing.JButton();
        cerrarsesion = new javax.swing.JButton();
        addMoneyButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        data = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        tlfLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        clave = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        emailTextField = new javax.swing.JTextField();
        dniTextField = new javax.swing.JTextField();
        tlfTextField = new javax.swing.JTextField();
        errorLabel1 = new javax.swing.JLabel();
        requirementsLabel = new javax.swing.JLabel();
        promocodeLabel = new javax.swing.JLabel();
        promocodeTextField = new javax.swing.JTextField();
        CCLabel = new javax.swing.JLabel();
        CCTextField = new javax.swing.JTextField();
        dayLabel = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        monthTextField = new javax.swing.JTextField();
        cvvTextField = new javax.swing.JTextField();
        cvvLabel = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        moneyLabel = new javax.swing.JLabel();
        moneyTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        userpfp = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        ParLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 250, 248));

        uppermenu.setBackground(new java.awt.Color(255, 250, 248));
        uppermenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uppermenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appname.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        appname.setForeground(new java.awt.Color(255, 90, 95));
        appname.setText("JavaBNB");
        uppermenu.add(appname, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 46, -1, -1));

        logo.setBackground(new java.awt.Color(255, 153, 153));
        logo.setBorderPainted(false);
        logo.setContentAreaFilled(false);
        logo.setDefaultCapable(false);
        logo.setFocusPainted(false);
        logo.setFocusable(false);
        logo.setRequestFocusEnabled(false);
        logo.setRolloverEnabled(false);
        logo.setVerifyInputWhenFocusTarget(false);
        uppermenu.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        logo1.setBackground(new java.awt.Color(255, 153, 153));
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airbnb logo - 100x100.png"))); // NOI18N
        logo1.setBorderPainted(false);
        logo1.setContentAreaFilled(false);
        logo1.setDefaultCapable(false);
        logo1.setFocusPainted(false);
        logo1.setFocusable(false);
        logo1.setRequestFocusEnabled(false);
        logo1.setRolloverEnabled(false);
        logo1.setVerifyInputWhenFocusTarget(false);
        uppermenu.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 23, 75, 83));

        mainscr.setBackground(new java.awt.Color(255, 90, 95));
        mainscr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainscr.setForeground(new java.awt.Color(255, 255, 255));
        mainscr.setText("Volver");
        mainscr.setBorderPainted(false);
        mainscr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainscr.setPreferredSize(new java.awt.Dimension(80, 30));
        mainscr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainscrActionPerformed(evt);
            }
        });
        uppermenu.add(mainscr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 39, 88, 39));

        cerrarsesion.setBackground(new java.awt.Color(255, 90, 95));
        cerrarsesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cerrarsesion.setForeground(new java.awt.Color(255, 255, 255));
        cerrarsesion.setText("Cerrar sesión");
        cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionActionPerformed(evt);
            }
        });
        uppermenu.add(cerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 39, 106, 39));

        addMoneyButton.setBackground(new java.awt.Color(255, 90, 95));
        addMoneyButton.setForeground(new java.awt.Color(255, 255, 255));
        addMoneyButton.setText("Añadir dinero");
        addMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoneyButtonActionPerformed(evt);
            }
        });
        uppermenu.add(addMoneyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 39, 118, 39));

        jPanel1.setBackground(new java.awt.Color(255, 250, 248));

        data.setBackground(new java.awt.Color(255, 250, 248));
        data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        data.setMaximumSize(new java.awt.Dimension(306, 307));
        data.setPreferredSize(new java.awt.Dimension(306, 400));
        data.setRequestFocusEnabled(false);
        data.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabel.setText("Correo electrónico:");
        data.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 17, -1, -1));

        dniLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dniLabel.setText("DNI:");
        data.add(dniLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 51, -1, -1));

        tlfLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tlfLabel.setText("Teléfono:");
        data.add(tlfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 85, -1, -1));

        passLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passLabel.setText("Contraseña:");
        data.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 387, -1, -1));

        clave.setText("contraseña1");
        data.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 387, 143, -1));

        jButton1.setBackground(new java.awt.Color(255, 90, 95));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Editar datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        data.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 466, 113, 34));

        emailTextField.setEditable(false);
        data.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 17, 139, -1));

        dniTextField.setEditable(false);
        data.add(dniTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 51, 83, -1));

        tlfTextField.setEditable(false);
        data.add(tlfTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 85, -1, -1));

        errorLabel1.setBackground(new java.awt.Color(255, 90, 95));
        errorLabel1.setForeground(new java.awt.Color(255, 90, 95));
        errorLabel1.setText("Alguno de los datos no cumple el formato requerido, o no es válido");
        errorLabel1.setEnabled(false);
        errorLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel1PropertyChange(evt);
            }
        });
        data.add(errorLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 506, -1, -1));

        requirementsLabel.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        requirementsLabel.setForeground(new java.awt.Color(102, 102, 102));
        requirementsLabel.setText("Al menos una letra mayúscula, minúscula, dígitos y 8 caracteres de longitud");
        data.add(requirementsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 415, -1, -1));

        promocodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        promocodeLabel.setText("Código promocional:");
        data.add(promocodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 119, -1, -1));

        promocodeTextField.setEditable(false);
        data.add(promocodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 119, -1, -1));

        CCLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CCLabel.setText("Tarjeta de crédito:");
        data.add(CCLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 153, -1, -1));

        CCTextField.setEditable(false);
        data.add(CCTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 153, 216, -1));

        dayLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dayLabel.setText("Día:");
        data.add(dayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 187, -1, -1));

        monthLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monthLabel.setText("Mes:");
        data.add(monthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 227, -1, -1));

        yearLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yearLabel.setText("Año:");
        data.add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 267, -1, -1));

        dayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTextFieldActionPerformed(evt);
            }
        });
        data.add(dayTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 187, -1, -1));

        monthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextFieldActionPerformed(evt);
            }
        });
        data.add(monthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 227, -1, -1));

        cvvTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvTextFieldActionPerformed(evt);
            }
        });
        data.add(cvvTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 307, -1, -1));

        cvvLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cvvLabel.setText("CVV:");
        data.add(cvvLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 307, -1, -1));

        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });
        data.add(yearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 267, -1, -1));

        moneyLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        moneyLabel.setText("Saldo:");
        data.add(moneyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 347, -1, -1));

        moneyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyTextFieldActionPerformed(evt);
            }
        });
        data.add(moneyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 347, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 90, 95));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Editar datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        data.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 466, 113, 34));

        userpfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (2).jpg"))); // NOI18N
        userpfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpfpActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        username.setForeground(new java.awt.Color(255, 90, 95));
        username.setText("XXXXXX");

        ParLabel.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        ParLabel.setForeground(new java.awt.Color(102, 102, 102));
        ParLabel.setText("Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userpfp, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(username))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(ParLabel)))
                .addGap(70, 70, 70)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(userpfp, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(username)
                        .addGap(14, 14, 14)
                        .addComponent(ParLabel))
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(uppermenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(uppermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void mainscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainscrActionPerformed
        App.loadMainScreen();
    }//GEN-LAST:event_mainscrActionPerformed

    private void cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionActionPerformed
        Sesion.cerrarSesion();
        App.cardLayout.show(App.cards, "Pantalla login");
    }//GEN-LAST:event_cerrarsesionActionPerformed

    private void addMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoneyButtonActionPerformed
        // Verifica si el usuario actual es un Particular
        if (Sesion.user instanceof Particular) {
            Particular particular = (Particular) Sesion.user;
            Tarjeta tarjeta = particular.getTarjetaCredito();
            try {
                // Verifica si el Particular tiene una tarjeta de crédito asociada
                if (tarjeta != null) {
                    double saldoañadido;
                    String notaIntroducida = JOptionPane.showInputDialog(this, "Introduzca la cantidad de dinero a añadir:");
                    saldoañadido = Double.parseDouble(notaIntroducida);

                    // Incrementa el saldo de la tarjeta
                    tarjeta.incrementarSaldo(saldoañadido);
                    moneyTextField.setText(String.valueOf(tarjeta.getSaldo()));
                    // Actualiza la interfaz de usuario para mostrar el nuevo saldo (si tienes una etiqueta o campo de texto para el saldo)

                    System.out.println("Saldo añadido. Nuevo saldo: " + tarjeta.getSaldo());
                } else {
                    System.out.println("El usuario no tiene una tarjeta de crédito asociada.");
                }

            } catch (NumberFormatException nfe) {
                System.out.println("Error del formato: " + nfe.getMessage());
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());

            }
        } else {
            System.out.println("El usuario actual no es un cliente particular.");
        }

    }//GEN-LAST:event_addMoneyButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jButton1.getText().equals("Editar datos")) {
            // Si el botón está en modo "Editar datos", establece los campos de texto como editables
            emailTextField.setEditable(true);
            clave.setEditable(true);
            tlfTextField.setEditable(true);
            if (Sesion.esUsuarioVip()) {

                promocodeTextField.setEditable(false);
            } else {
                promocodeTextField.setEditable(true);
            }
            // Cambiar el texto del botón a "Aceptar"
            jButton1.setText("Aceptar");
        } else {
            // Si el botón está en modo "Aceptar", establece los campos de texto como no editables
            emailTextField.setEditable(false);
            clave.setEditable(false);
            tlfTextField.setEditable(false);
            promocodeTextField.setEditable(false);

            jButton1.setText("Editar datos");

            String email = emailTextField.getText();
            char[] passwordCharArray = clave.getPassword();
            String password = new String(passwordCharArray);
            String telefono = tlfTextField.getText();
            String promocode = promocodeTextField.getText();

            boolean valido = true;

            // Verificar el correo electrónico
            if (!Validacion.validarEmail(email)) {
                errorLabel1.setVisible(true);
                emailTextField.setText("");
                valido = false;
            } // Verificar la contraseña
            else if (!Validacion.validarContraseña(password)) {
                errorLabel1.setVisible(true);
                clave.setText("");
                valido = false;
            } // Verificar el teléfono
            else if (!Validacion.validarTelefono(telefono)) {
                errorLabel1.setVisible(true);
                tlfTextField.setText("");
                valido = false;
            }

            // Verificar el código promocional
            if (!Validacion.validarPromocode(promocode)) {
                errorLabel1.setVisible(true);
                promocodeTextField.setText("");
                valido = false;
            } else {
                errorLabel1.setVisible(false);
            }

            if (valido) {
                errorLabel1.setVisible(false);

                Sesion.user.setCorreo(email);
                Sesion.user.setTelefono(telefono);
                Sesion.user.setClave(password);

                // Verificar y actualizar el estado VIP
                if (Sesion.hacerVipSiPromocodeValido(promocode)) {
                    System.out.println("El usuario ha sido actualizado a VIP.");
                }

                System.out.println(Sesion.user.toString());
            } else {
                errorLabel1.setVisible(false);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void errorLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel1PropertyChange

    private void dayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextFieldActionPerformed

    private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldActionPerformed

    private void cvvTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void moneyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void userpfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userpfpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userpfpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCLabel;
    private javax.swing.JTextField CCTextField;
    private javax.swing.JLabel ParLabel;
    private javax.swing.JButton addMoneyButton;
    private javax.swing.JLabel appname;
    private javax.swing.JButton cerrarsesion;
    private javax.swing.JPasswordField clave;
    private javax.swing.JLabel cvvLabel;
    private javax.swing.JTextField cvvTextField;
    private javax.swing.JPanel data;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel errorLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logo;
    private javax.swing.JButton logo1;
    private javax.swing.JButton mainscr;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JTextField moneyTextField;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel promocodeLabel;
    private javax.swing.JTextField promocodeTextField;
    private javax.swing.JLabel requirementsLabel;
    private javax.swing.JLabel tlfLabel;
    private javax.swing.JTextField tlfTextField;
    private javax.swing.JPanel uppermenu;
    private javax.swing.JLabel username;
    private javax.swing.JButton userpfp;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
