/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package Visual;

import Programa.Host;
import Programa.Inicio;
import Programa.Validate;

/**
 * Panel que muestra el perfil del anfitrión actual.
 */
public class PerfilAnfitrion extends javax.swing.JPanel {

    /**
     * Crea un nuevo panel para mostrar el perfil del anfitrión.
     */
    public PerfilAnfitrion() {
        initComponents();
        errorLabel1.setVisible(false);
        requirementsLabel.setVisible(false);
    }

    /**
     * Actualiza la información mostrada en el perfil del anfitrión.
     */
    public void update() {
        // Verifica si el usuario actual está inicializado
        if (Inicio.user != null) {
            // Establece los valores de los campos de texto con la información del usuario
            dniTextField.setText(Inicio.user.getDni());
            username.setText(Inicio.user.getNombre().toUpperCase());
            emailTextField.setText(Inicio.user.getCorreo());
            passTextField.setText(Inicio.user.getpassw());
            tlfTextField.setText(Inicio.user.getTelefono());

            // Verifica si el usuario es un super anfitrión y actualiza la etiqueta correspondiente
            if (((Host) Inicio.user).isSuperAnfitrion()) {
                hostlabel.setText("Super anfitrión");
            } else {
                hostlabel.setText("Anfitrión");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        uppermenu = new javax.swing.JPanel();
        signOutButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        appname1 = new javax.swing.JLabel();
        data = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        tlfLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        passTextField = new javax.swing.JPasswordField();
        editUserButton = new javax.swing.JButton();
        emailTextField = new javax.swing.JTextField();
        dniTextField = new javax.swing.JTextField();
        tlfTextField = new javax.swing.JTextField();
        errorLabel1 = new javax.swing.JLabel();
        requirementsLabel = new javax.swing.JLabel();
        hostlabel = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        photoLabel1 = new javax.swing.JLabel();
        perfilLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 236, 217));
        jPanel2.setMaximumSize(new java.awt.Dimension(1020, 828));
        jPanel2.setPreferredSize(new java.awt.Dimension(1020, 828));

        uppermenu.setBackground(new java.awt.Color(255, 153, 102));
        uppermenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signOutButton.setBackground(new java.awt.Color(255, 90, 95));
        signOutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(255, 255, 255));
        signOutButton.setText("Cerrar sesion");
        signOutButton.setBorderPainted(false);
        signOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signOutButton.setPreferredSize(new java.awt.Dimension(80, 30));
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });
        uppermenu.add(signOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 17, 109, 40));

        returnButton.setBackground(new java.awt.Color(255, 90, 95));
        returnButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnButton.setForeground(new java.awt.Color(255, 255, 255));
        returnButton.setText("Volver");
        returnButton.setBorderPainted(false);
        returnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnButton.setPreferredSize(new java.awt.Dimension(80, 30));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        uppermenu.add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 17, 88, 39));

        appname1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        appname1.setText("JavaBNB");
        uppermenu.add(appname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 20, -1, -1));

        data.setBackground(new java.awt.Color(255, 250, 248));
        data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        data.setMaximumSize(new java.awt.Dimension(306, 307));
        data.setPreferredSize(new java.awt.Dimension(306, 150));
        data.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 14)); // NOI18N
        emailLabel.setText("Correo electrónico:");
        data.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        dniLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 14)); // NOI18N
        dniLabel.setText("DNI:");
        data.add(dniLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        tlfLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 14)); // NOI18N
        tlfLabel.setText("Teléfono:");
        data.add(tlfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        passLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 14)); // NOI18N
        passLabel.setText("Contraseña:");
        data.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        passTextField.setText("contraseña1");
        data.add(passTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 140, -1));

        editUserButton.setBackground(new java.awt.Color(255, 153, 102));
        editUserButton.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        editUserButton.setForeground(new java.awt.Color(255, 255, 255));
        editUserButton.setText("Editar datos");
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });
        data.add(editUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 112, 34));

        emailTextField.setEditable(false);
        data.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 270, -1));

        dniTextField.setEditable(false);
        data.add(dniTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 370, -1));

        tlfTextField.setEditable(false);
        data.add(tlfTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 340, -1));

        errorLabel1.setBackground(new java.awt.Color(255, 90, 95));
        errorLabel1.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        errorLabel1.setForeground(new java.awt.Color(255, 90, 95));
        errorLabel1.setText("Alguno de los datos no es válido");
        errorLabel1.setEnabled(false);
        errorLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel1PropertyChange(evt);
            }
        });
        data.add(errorLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        requirementsLabel.setFont(new java.awt.Font("Noto Sans", 2, 10)); // NOI18N
        requirementsLabel.setForeground(new java.awt.Color(102, 102, 102));
        requirementsLabel.setText("Al menos una mayúscula, minúcula, números y de longitud 8");
        data.add(requirementsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        hostlabel.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        hostlabel.setForeground(new java.awt.Color(102, 102, 102));
        hostlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hostlabel.setText("Anfitrión");

        username.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        username.setForeground(new java.awt.Color(255, 90, 95));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("OOOOOOO");

        photoLabel1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        photoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/logo.png"))); // NOI18N

        perfilLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 48)); // NOI18N
        perfilLabel.setForeground(new java.awt.Color(255, 153, 102));
        perfilLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perfilLabel.setText("Perfil Anfitrión");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uppermenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(perfilLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(data, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hostlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(photoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(uppermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(username)
                        .addGap(18, 18, 18)
                        .addComponent(hostlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(photoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(perfilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        Inicio.cerrarSesion();
        Aplicacion.cardLayout.show(Aplicacion.cards, "Pantalla login");
    }//GEN-LAST:event_signOutButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        Aplicacion.cargaPantallaPrincipal();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserButtonActionPerformed
        // Verifica el texto actual del botón
if (editUserButton.getText().equals("Editar datos")) {
    // Si el botón está en modo "Editar datos"
    // Establece los campos de texto como editables
    emailTextField.setEditable(true);
    passTextField.setEditable(true);
    tlfTextField.setEditable(true);

    // Cambia el texto del botón a "Aceptar"
    editUserButton.setText("Aceptar");
} else {
    // Si el botón está en modo "Aceptar"
    // Establece los campos de texto como no editables
    emailTextField.setEditable(false);
    passTextField.setEditable(false);
    tlfTextField.setEditable(false);

    // Cambia el texto del botón a "Editar datos"
    editUserButton.setText("Editar datos");

    // Verifica la validez de los datos ingresados
    String email = emailTextField.getText();

    // No utilizar getText en la passwordField porque está "deprecated"
    char[] passwCharArray = passTextField.getPassword();
    String password = new String(passwCharArray);
    String telefono = tlfTextField.getText();

    boolean datosValidos = true;

    // Verifica el correo electrónico
    if (!Validate.validarEmail(email)) {
        errorLabel1.setVisible(true);
        emailTextField.setText("");
        datosValidos = false;
    } // Verifica la contraseña
    else if (!Validate.validarContraseña(password)) {
        errorLabel1.setVisible(true);
        passTextField.setText("");
        datosValidos = false;
    } // Verifica el teléfono
    else if (!Validate.validarTelefono(telefono)) {
        errorLabel1.setVisible(true);
        tlfTextField.setText("");
        datosValidos = false;
    } else {
        errorLabel1.setVisible(false);
    }

    // Si todos los datos son válidos, guardar los cambios
    if (datosValidos) {
        errorLabel1.setVisible(false);
        Inicio.user.setCorreo(email);
        Inicio.user.setTelefono(telefono);
        Inicio.user.setpassw(password);
        System.out.println(Inicio.user);
    } else {
        errorLabel1.setVisible(true);
    }
}

    }//GEN-LAST:event_editUserButtonActionPerformed

    private void errorLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel1PropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appname1;
    private javax.swing.JPanel data;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JButton editUserButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel errorLabel1;
    private javax.swing.JLabel hostlabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passTextField;
    private javax.swing.JLabel perfilLabel;
    private javax.swing.JLabel photoLabel1;
    private javax.swing.JLabel requirementsLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton signOutButton;
    private javax.swing.JLabel tlfLabel;
    private javax.swing.JTextField tlfTextField;
    private javax.swing.JPanel uppermenu;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
