/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package Visual;

import Programa.Host;
import Programa.Particular;
import Programa.Inicio;
import Programa.Credito;
import Programa.Validate;
import java.time.LocalDate;

public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    public Registro() {
        initComponents();
        errorLabel.setVisible(false);
        errorLabel1.setVisible(false);
        errorLabel2.setVisible(false);
        errorLabel6.setVisible(false);
        errorLabel3.setVisible(false);
        errorLabel8.setVisible(false);
        errorLabel5.setVisible(false);
        errorLabel4.setVisible(false);
        noselectLabel.setVisible(false);
        requirementsLabel.setVisible(false);
        monthTextField.setVisible(false);
        dayTextField.setVisible(false);
        yearTextField.setVisible(false);
        cvvTextField.setVisible(false);
        CCTextField.setVisible(false);

        promocodeTextField.setVisible(false);
        promocodeLabel.setVisible(false);

        CCLabel.setVisible(false);
        dayLabel.setVisible(false);
        monthLabel.setVisible(false);
        yearLabel.setVisible(false);
        cvvLabel.setVisible(false);
        noselectLabel.setVisible(false);
        userExiste.setVisible(false);
        statementLabel.setVisible(false);
    }

    public void resetText() {
        userTextField1.setText("");
        DNITextField.setText("");
        emailTextField.setText("");
        passwordTextField.setText("");
        tlfTextField.setText("");
        CCTextField.setText("");
        cvvTextField.setText("");
        promocodeTextField.setText("");
        monthTextField.setText("");
        dayTextField.setText("");
        yearTextField.setText("");
        selectComboBox.setSelectedItem("Seleccione entre:");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createaccLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        promocodeTextField = new javax.swing.JTextField();
        promocodeLabel = new javax.swing.JLabel();
        tlfLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        selectComboBox = new javax.swing.JComboBox<>();
        existaccLabel = new javax.swing.JLabel();
        noselectLabel = new javax.swing.JLabel();
        DNILabel = new javax.swing.JLabel();
        DNITextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        tlfTextField = new javax.swing.JTextField();
        dayLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        CCLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        errorLabel1 = new javax.swing.JLabel();
        errorLabel3 = new javax.swing.JLabel();
        errorLabel8 = new javax.swing.JLabel();
        errorLabel5 = new javax.swing.JLabel();
        errorLabel6 = new javax.swing.JLabel();
        errorLabel2 = new javax.swing.JLabel();
        requirementsLabel = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        cvvTextField = new javax.swing.JTextField();
        CCTextField = new javax.swing.JTextField();
        monthLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        cvvLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        statementLabel2 = new javax.swing.JLabel();
        monthTextField = new javax.swing.JTextField();
        statementLabel = new javax.swing.JLabel();
        userExiste = new javax.swing.JLabel();
        userLabel1 = new javax.swing.JLabel();
        userTextField1 = new javax.swing.JTextField();
        errorLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 250, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createaccLabel.setBackground(new java.awt.Color(255, 90, 95));
        createaccLabel.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        createaccLabel.setForeground(new java.awt.Color(255, 90, 95));
        createaccLabel.setText("Cree su cuenta en JavaBNB");
        jPanel1.add(createaccLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 16, -1, -1));

        subtitleLabel.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        subtitleLabel.setForeground(new java.awt.Color(255, 90, 95));
        subtitleLabel.setText("Anfitrión o cliente: ¡elija su función!");
        jPanel1.add(subtitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 83, -1, 41));

        photoLabel.setBackground(new java.awt.Color(255, 90, 95));
        photoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airbnb logo - 100x100.png"))); // NOI18N
        photoLabel.setBorderPainted(false);
        photoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        photoLabel.setDefaultCapable(false);
        photoLabel.setFocusPainted(false);
        photoLabel.setFocusable(false);
        photoLabel.setRequestFocusEnabled(false);
        photoLabel.setRolloverEnabled(false);
        photoLabel.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(photoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 144, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("REGISTRO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 273, -1, -1));

        promocodeTextField.setToolTipText("");
        promocodeTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        promocodeTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        promocodeTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                promocodeTextFieldMousePressed(evt);
            }
        });
        promocodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promocodeTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(promocodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 1036, 418, 27));

        promocodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        promocodeLabel.setForeground(new java.awt.Color(102, 102, 102));
        promocodeLabel.setText("Código promocional *");
        jPanel1.add(promocodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 1004, -1, 22));

        tlfLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tlfLabel.setForeground(new java.awt.Color(102, 102, 102));
        tlfLabel.setText("Teléfono *");
        jPanel1.add(tlfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 462, -1, -1));

        passwordTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passwordTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordTextFieldMousePressed(evt);
            }
        });
        jPanel1.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 768, 418, 27));

        registerButton.setBackground(new java.awt.Color(255, 90, 95));
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Registrarse");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 1177, 122, 44));

        selectComboBox.setBackground(new java.awt.Color(255, 90, 95));
        selectComboBox.setForeground(new java.awt.Color(255, 255, 255));
        selectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione entre:", "Anfitrion", "Particular" }));
        selectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(selectComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 317, -1, -1));

        existaccLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        existaccLabel.setForeground(new java.awt.Color(255, 90, 95));
        existaccLabel.setText("¿Ya tiene una cuenta?");
        existaccLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        existaccLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                existaccLabelMouseClicked(evt);
            }
        });
        jPanel1.add(existaccLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 1239, -1, -1));

        noselectLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        noselectLabel.setForeground(new java.awt.Color(255, 0, 0));
        noselectLabel.setText("Alguno de los datos no es válido. Rellene todos los campos correctamente");
        jPanel1.add(noselectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 1125, -1, -1));

        DNILabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DNILabel.setForeground(new java.awt.Color(102, 102, 102));
        DNILabel.setText("DNI *");
        jPanel1.add(DNILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 554, -1, -1));

        DNITextField.setToolTipText("");
        DNITextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DNITextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DNITextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DNITextFieldMousePressed(evt);
            }
        });
        DNITextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNITextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DNITextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 584, 418, 27));

        emailTextField.setToolTipText("");
        emailTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTextFieldMousePressed(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 676, 418, 27));

        tlfTextField.setToolTipText("");
        tlfTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tlfTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tlfTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tlfTextFieldMousePressed(evt);
            }
        });
        tlfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlfTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(tlfTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 492, 418, 27));

        dayLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dayLabel.setForeground(new java.awt.Color(102, 102, 102));
        dayLabel.setText("Día:");
        jPanel1.add(dayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 931, -1, -1));

        passLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passLabel.setForeground(new java.awt.Color(102, 102, 102));
        passLabel.setText("Contraseña *");
        jPanel1.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 738, -1, -1));

        CCLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CCLabel.setForeground(new java.awt.Color(102, 102, 102));
        CCLabel.setText("Tarjeta de crédito *");
        jPanel1.add(CCLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 857, -1, -1));

        errorLabel.setText("Seleccione algo, por favor");
        errorLabel.setEnabled(false);
        errorLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabelPropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 352, -1, -1));

        errorLabel1.setText("Esta tarjeta no existe");
        errorLabel1.setEnabled(false);
        errorLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel1PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 988, -1, -1));

        errorLabel3.setText("Contraseña poco segura");
        errorLabel3.setEnabled(false);
        errorLabel3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel3PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 803, -1, -1));

        errorLabel8.setText("Este código promocional no existe");
        errorLabel8.setEnabled(false);
        errorLabel8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel8PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 1071, -1, -1));

        errorLabel5.setText("Formato no válido");
        errorLabel5.setEnabled(false);
        errorLabel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel5PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 527, -1, -1));

        errorLabel6.setText("Formato no válido");
        errorLabel6.setEnabled(false);
        errorLabel6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel6PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 711, -1, -1));

        errorLabel2.setText("Formato no válido");
        errorLabel2.setEnabled(false);
        errorLabel2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel2PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 619, -1, -1));

        requirementsLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        requirementsLabel.setForeground(new java.awt.Color(102, 102, 102));
        requirementsLabel.setText("Al menos una letra mayúscula, minúscula, dígitos y 8 caracteres de longitud");
        jPanel1.add(requirementsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 830, -1, -1));

        dayTextField.setToolTipText("");
        dayTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dayTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dayTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dayTextFieldMousePressed(evt);
            }
        });
        dayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(dayTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 926, 91, 27));

        yearTextField.setToolTipText("");
        yearTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yearTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        yearTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                yearTextFieldMousePressed(evt);
            }
        });
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(yearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 926, 91, 27));

        cvvTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cvvTextField.setToolTipText("");
        cvvTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cvvTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cvvTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cvvTextFieldMousePressed(evt);
            }
        });
        cvvTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(cvvTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 926, 91, 27));

        CCTextField.setToolTipText("");
        CCTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CCTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CCTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CCTextFieldMousePressed(evt);
            }
        });
        CCTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(CCTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 887, 418, 27));

        monthLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monthLabel.setForeground(new java.awt.Color(102, 102, 102));
        monthLabel.setText("Mes:");
        jPanel1.add(monthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 931, -1, -1));

        yearLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(102, 102, 102));
        yearLabel.setText("Año:");
        jPanel1.add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 931, -1, -1));

        cvvLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cvvLabel.setForeground(new java.awt.Color(102, 102, 102));
        cvvLabel.setText("CVV:");
        jPanel1.add(cvvLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 931, -1, -1));

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(102, 102, 102));
        emailLabel.setText("Correo *");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 646, -1, -1));

        statementLabel2.setForeground(new java.awt.Color(102, 102, 102));
        statementLabel2.setText("Nota: se deben rellenar todos los campos obligatorios (marcados con *)");
        jPanel1.add(statementLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 1098, -1, -1));

        monthTextField.setToolTipText("");
        monthTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monthTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        monthTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                monthTextFieldMousePressed(evt);
            }
        });
        monthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(monthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 926, 91, 27));

        statementLabel.setForeground(new java.awt.Color(102, 102, 102));
        statementLabel.setText("Introduzca la fecha de caducidad y el CVV");
        jPanel1.add(statementLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 966, -1, -1));

        userExiste.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userExiste.setForeground(new java.awt.Color(0, 153, 51));
        userExiste.setText("Ya existe una cuenta asociada a este teléfono, DNI o correo. Por favor, inicie sesión.");
        jPanel1.add(userExiste, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 1141, -1, -1));

        userLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userLabel1.setForeground(new java.awt.Color(102, 102, 102));
        userLabel1.setText("Nombre completo *");
        jPanel1.add(userLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 368, -1, 22));

        userTextField1.setToolTipText("");
        userTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTextField1MousePressed(evt);
            }
        });
        userTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(userTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 400, 418, 27));

        errorLabel4.setText("Formato no válido");
        errorLabel4.setEnabled(false);
        errorLabel4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel4PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 435, -1, -1));

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void promocodeTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promocodeTextFieldMousePressed

    }//GEN-LAST:event_promocodeTextFieldMousePressed

    private void promocodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promocodeTextFieldActionPerformed

    }//GEN-LAST:event_promocodeTextFieldActionPerformed

    private void passwordTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTextFieldMousePressed

    }//GEN-LAST:event_passwordTextFieldMousePressed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed

        //Inicializamos atributos
        String nombre = userTextField1.getText();
        String dni = DNITextField.getText();
        String correo = emailTextField.getText();

        char[] passwordCharArray = passwordTextField.getPassword();
        String clave = new String(passwordCharArray);
        String telefono = tlfTextField.getText();
        String numtarjeta = CCTextField.getText();
        String cvv = cvvTextField.getText();
        String promocode = promocodeTextField.getText();
        double saldo = 1000; //el saldo inicial de todos los clientes será de 1000
        boolean valido = true;
        userExiste.setVisible(false);
        int dia = -1;
        int mes = -1;
        int año = -1;

        if (!Validate.validarNombre(nombre)) {
            errorLabel4.setVisible(true);
            valido = false;
            promocodeTextField.setText("");
        } else {errorLabel4.setVisible(false);}

        if (!Validate.validarDNI(dni)) {
            errorLabel2.setVisible(true);
            valido = false;
            DNITextField.setText("");
        } else { errorLabel2.setVisible(false);}

        if (!Validate.validarEmail(correo)) {
            errorLabel6.setVisible(true);
            valido = false;
            emailTextField.setText("");
        } else {errorLabel6.setVisible(false);}

        if (!Validate.validarTelefono(telefono)) {
            errorLabel5.setVisible(true);
            valido = false;
            tlfTextField.setText("");
        } else { errorLabel5.setVisible(false);}

        if (!Validate.validarContraseña(clave)) {
            errorLabel3.setVisible(true);
            requirementsLabel.setVisible(true);
            passwordTextField.setText("");
            valido = false;
        } else {  errorLabel3.setVisible(false); }

        String selectedOption = (String) selectComboBox.getSelectedItem();
        boolean usuarioExiste = Validate.comprobarExistenciaCliente(correo.toLowerCase(), dni, telefono);

        if (selectedOption.equals("Seleccione entre:")) {
            noselectLabel.setVisible(true);
            userExiste.setVisible(false);

        } else if (usuarioExiste) {
            userExiste.setVisible(true);
            noselectLabel.setVisible(false);

        } else if (selectedOption.equals("Anfitrion") && valido) {
            noselectLabel.setVisible(false);
            Host nuevoAnfitrion = new Host(dni, nombre, correo.toLowerCase(), clave, telefono);
            Inicio.registrarCliente(nuevoAnfitrion);
            resetText();
            Aplicacion.loadMainScreen();
        } else if (selectedOption.equals("Anfitrion") && !valido) {
            noselectLabel.setVisible(true);

        } else if (selectedOption.equals("Particular")) {
            try {
                if (!monthTextField.getText().isEmpty()) {
                    mes = Integer.parseInt(monthTextField.getText());
                } else {System.err.println("El campo de día está vacío."); }

                if (!dayTextField.getText().isEmpty()) {
                    dia = Integer.parseInt(dayTextField.getText());
                } else { System.err.println("El campo de mes está vacío.");}

                if (!yearTextField.getText().isEmpty()) {
                    año = Integer.parseInt(yearTextField.getText());
                } else {  System.err.println("El campo de año está vacío.");}

            } catch (NumberFormatException e) {
                System.err.println("Error al convertir el texto a número.");
                dia = -1;
                mes = -1;
                año = -1;
            }

            if (!Validate.validarTarjeta(numtarjeta, dia, mes, año, cvv)) {
                errorLabel1.setVisible(true);
                valido = false;
                monthTextField.setText("");
                dayTextField.setText("");
                yearTextField.setText("");
                cvvTextField.setText("");
            } else {

                errorLabel1.setVisible(false);
            }

            if (!Validate.validarPromocode(promocode)) {
                errorLabel8.setVisible(true);
                promocodeTextField.setText("");
                valido = false;
            } else {
                errorLabel8.setVisible(false);
            }

            if (valido) {
                noselectLabel.setVisible(false);
                boolean vip = Validate.validarVipPromocode(promocode);
                LocalDate fechaCaducidad = LocalDate.of(año, mes, dia);
                Credito tarjeta = new Credito(nombre, numtarjeta, dia, mes, año, fechaCaducidad, cvv, saldo);
                Particular nuevoParticular = new Particular(tarjeta, vip, dni, nombre, correo.toLowerCase(), clave, telefono);
                Inicio.registrarCliente(nuevoParticular);
                resetText();
                Aplicacion.loadMainScreen();
                return;
            }
            noselectLabel.setVisible(true);

        }

    }//GEN-LAST:event_registerButtonActionPerformed

    private void selectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectComboBoxActionPerformed
        //Qué ocurre al elegir una opción u otra
        String selectedOption = (String) selectComboBox.getSelectedItem();
        if (selectedOption.equals("Particular")) {
            monthTextField.setVisible(true);
            dayLabel.setVisible(true);
            dayTextField.setVisible(true);
            monthLabel.setVisible(true);
            yearTextField.setVisible(true);
            yearLabel.setVisible(true);
            cvvTextField.setVisible(true);
            cvvLabel.setVisible(true);
            promocodeTextField.setVisible(true);

            CCTextField.setVisible(true);
            CCLabel.setVisible(true);
            noselectLabel.setVisible(true);
            statementLabel.setVisible(true);
            promocodeLabel.setVisible(true);
            noselectLabel.setVisible(false);

        } else {
            monthTextField.setVisible(false);
            dayLabel.setVisible(false);
            dayTextField.setVisible(false);
            monthLabel.setVisible(false);
            yearTextField.setVisible(false);
            yearLabel.setVisible(false);
            cvvTextField.setVisible(false);
            cvvLabel.setVisible(false);
            CCTextField.setVisible(false);
            CCLabel.setVisible(false);

            promocodeLabel.setVisible(false);
            promocodeTextField.setVisible(false);

            noselectLabel.setVisible(false);

            errorLabel.setVisible(false);
            errorLabel1.setVisible(false);
            errorLabel2.setVisible(false);
            errorLabel6.setVisible(false);
            errorLabel3.setVisible(false);
            errorLabel8.setVisible(false);
            errorLabel5.setVisible(false);
            statementLabel.setVisible(false);
            errorLabel4.setVisible(false);

        }
    }//GEN-LAST:event_selectComboBoxActionPerformed

    private void existaccLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_existaccLabelMouseClicked
        resetText();
        Aplicacion.cardLayout.show(Aplicacion.cards, "Pantalla login");
    }//GEN-LAST:event_existaccLabelMouseClicked

    private void DNITextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNITextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNITextFieldMousePressed

    private void DNITextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNITextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNITextFieldActionPerformed

    private void emailTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldMousePressed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void tlfTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlfTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlfTextFieldMousePressed

    private void tlfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlfTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlfTextFieldActionPerformed

    private void errorLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabelPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabelPropertyChange

    private void errorLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel1PropertyChange

    private void errorLabel3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel3PropertyChange

    private void errorLabel8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel8PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel8PropertyChange

    private void errorLabel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel5PropertyChange

    private void errorLabel6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel6PropertyChange

    private void errorLabel2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel2PropertyChange

    private void dayTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dayTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextFieldMousePressed

    private void dayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextFieldActionPerformed

    private void yearTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldMousePressed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void cvvTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvvTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldMousePressed

    private void cvvTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldActionPerformed

    private void CCTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCTextFieldMousePressed

    private void CCTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCTextFieldActionPerformed

    private void monthTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldMousePressed

    private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldActionPerformed

    private void userTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextField1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextField1MousePressed

    private void userTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextField1ActionPerformed

    private void errorLabel4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel4PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel4PropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCLabel;
    private javax.swing.JTextField CCTextField;
    private javax.swing.JLabel DNILabel;
    private javax.swing.JTextField DNITextField;
    private javax.swing.JLabel createaccLabel;
    private javax.swing.JLabel cvvLabel;
    private javax.swing.JTextField cvvTextField;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel errorLabel1;
    private javax.swing.JLabel errorLabel2;
    private javax.swing.JLabel errorLabel3;
    private javax.swing.JLabel errorLabel4;
    private javax.swing.JLabel errorLabel5;
    private javax.swing.JLabel errorLabel6;
    private javax.swing.JLabel errorLabel8;
    private javax.swing.JLabel existaccLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel noselectLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton photoLabel;
    private javax.swing.JLabel promocodeLabel;
    private javax.swing.JTextField promocodeTextField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel requirementsLabel;
    private javax.swing.JComboBox<String> selectComboBox;
    private javax.swing.JLabel statementLabel;
    private javax.swing.JLabel statementLabel2;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel tlfLabel;
    private javax.swing.JTextField tlfTextField;
    private javax.swing.JLabel userExiste;
    private javax.swing.JLabel userLabel1;
    private javax.swing.JTextField userTextField1;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
