/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package Visual;

import Programa.Host;
import Programa.Particular;
import Programa.Inicio;
import Programa.Credito;
import Programa.Validate;
import java.time.LocalDate;

/**
 * Panel de registro de nuevos usuarios.
 */

public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    public Registro() {
        initComponents();
        // Oculta los mensajes de error y otros campos que no son necesarios inicialmente
        errorLabel.setVisible(false);
        errorLabel1.setVisible(false);
        errorLabel2.setVisible(false);
        errorLabel6.setVisible(false);
        errorLabel3.setVisible(false);
        errorLabel8.setVisible(false);
        errorLabel5.setVisible(false);
        errorLabel4.setVisible(false);
        noselectLabel.setVisible(false);
        requirementsLabel.setVisible(false);
        monthTextField.setVisible(false);
        dayTextField.setVisible(false);
        yearTextField.setVisible(false);
        cvvTextField.setVisible(false);
        CCTextField.setVisible(false);

        promocodeTextField.setVisible(false);
        promocodeLabel.setVisible(false);

        CCLabel.setVisible(false);
        dayLabel.setVisible(false);
        monthLabel.setVisible(false);
        yearLabel.setVisible(false);
        cvvLabel.setVisible(false);
        noselectLabel.setVisible(false);
        userExiste.setVisible(false);
        statementLabel.setVisible(false);
    }

    /**
     * Restablece los campos de texto del formulario.
     */
    public void reseteoTexto() {
        // Restablece los campos de texto a su valor predeterminado
        userTextField1.setText("");
        DNITextField.setText("");
        emailTextField.setText("");
        passwordTextField.setText("");
        tlfTextField.setText("");
        CCTextField.setText("");
        cvvTextField.setText("");
        promocodeTextField.setText("");
        monthTextField.setText("");
        dayTextField.setText("");
        yearTextField.setText("");
        selectComboBox.setSelectedItem("Seleccione entre:");
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        subtitleLabel = new javax.swing.JLabel();
        promocodeTextField = new javax.swing.JTextField();
        promocodeLabel = new javax.swing.JLabel();
        tlfLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        selectComboBox = new javax.swing.JComboBox<>();
        existaccLabel = new javax.swing.JLabel();
        noselectLabel = new javax.swing.JLabel();
        DNILabel = new javax.swing.JLabel();
        DNITextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        tlfTextField = new javax.swing.JTextField();
        dayLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        CCLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        errorLabel1 = new javax.swing.JLabel();
        errorLabel3 = new javax.swing.JLabel();
        errorLabel8 = new javax.swing.JLabel();
        errorLabel5 = new javax.swing.JLabel();
        errorLabel6 = new javax.swing.JLabel();
        errorLabel2 = new javax.swing.JLabel();
        requirementsLabel = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        cvvTextField = new javax.swing.JTextField();
        CCTextField = new javax.swing.JTextField();
        monthLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        cvvLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        monthTextField = new javax.swing.JTextField();
        statementLabel = new javax.swing.JLabel();
        userExiste = new javax.swing.JLabel();
        userLabel1 = new javax.swing.JLabel();
        userTextField1 = new javax.swing.JTextField();
        errorLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        createaccLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 236, 217));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitleLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 18)); // NOI18N
        subtitleLabel.setForeground(new java.awt.Color(255, 102, 102));
        subtitleLabel.setText("Registrese como Particular o Anfitrión ->");
        jPanel1.add(subtitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 41));

        promocodeTextField.setBackground(new java.awt.Color(255, 236, 217));
        promocodeTextField.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        promocodeTextField.setToolTipText("");
        promocodeTextField.setBorder(null);
        promocodeTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        promocodeTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                promocodeTextFieldMousePressed(evt);
            }
        });
        promocodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promocodeTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(promocodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 418, 27));

        promocodeLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        promocodeLabel.setText("CÓDIGO PROMOCIONAL*");
        jPanel1.add(promocodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, 22));

        tlfLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        tlfLabel.setText("TELÉFONO*");
        jPanel1.add(tlfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        passwordTextField.setBackground(new java.awt.Color(255, 236, 217));
        passwordTextField.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        passwordTextField.setBorder(null);
        passwordTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordTextFieldMousePressed(evt);
            }
        });
        jPanel1.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 418, 27));

        registerButton.setBackground(new java.awt.Color(255, 153, 102));
        registerButton.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 14)); // NOI18N
        registerButton.setText("Registrarse");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 190, 44));

        selectComboBox.setBackground(new java.awt.Color(255, 102, 102));
        selectComboBox.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        selectComboBox.setForeground(new java.awt.Color(255, 255, 255));
        selectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione entre:", "Anfitrion", "Particular" }));
        selectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(selectComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        existaccLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        existaccLabel.setForeground(new java.awt.Color(255, 102, 102));
        existaccLabel.setText("¿Ya tienes cuenta? Inicia sesión");
        existaccLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        existaccLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                existaccLabelMouseClicked(evt);
            }
        });
        jPanel1.add(existaccLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        noselectLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        noselectLabel.setForeground(new java.awt.Color(255, 102, 102));
        noselectLabel.setText("Alguno de los datos no es válido. Rellene todos los campos correctamente");
        jPanel1.add(noselectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, -1));

        DNILabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        DNILabel.setText("DNI*");
        jPanel1.add(DNILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        DNITextField.setBackground(new java.awt.Color(255, 236, 217));
        DNITextField.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        DNITextField.setToolTipText("");
        DNITextField.setBorder(null);
        DNITextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DNITextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DNITextFieldMousePressed(evt);
            }
        });
        DNITextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNITextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DNITextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 418, 27));

        emailTextField.setBackground(new java.awt.Color(255, 236, 217));
        emailTextField.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        emailTextField.setToolTipText("");
        emailTextField.setBorder(null);
        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTextFieldMousePressed(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 418, 27));

        tlfTextField.setBackground(new java.awt.Color(255, 236, 217));
        tlfTextField.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        tlfTextField.setToolTipText("");
        tlfTextField.setBorder(null);
        tlfTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tlfTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tlfTextFieldMousePressed(evt);
            }
        });
        tlfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlfTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(tlfTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 418, 27));

        dayLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        dayLabel.setText("DÍA:");
        jPanel1.add(dayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        passLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        passLabel.setText("CONTRASEÑA*");
        jPanel1.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        CCLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        CCLabel.setText("TARJETA DE CRÉDITO*");
        jPanel1.add(CCLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        errorLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        errorLabel.setText("Seleccione algo, por favor");
        errorLabel.setEnabled(false);
        errorLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabelPropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, 20));

        errorLabel1.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        errorLabel1.setText("Esta tarjeta no existe");
        errorLabel1.setEnabled(false);
        errorLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel1PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, -1, -1));

        errorLabel3.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        errorLabel3.setText("Contraseña poco segura");
        errorLabel3.setEnabled(false);
        errorLabel3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel3PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, -1, -1));

        errorLabel8.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        errorLabel8.setText("Este código promocional no existe");
        errorLabel8.setEnabled(false);
        errorLabel8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel8PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        errorLabel5.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        errorLabel5.setText("Formato no válido");
        errorLabel5.setEnabled(false);
        errorLabel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel5PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        errorLabel6.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        errorLabel6.setText("Formato no válido");
        errorLabel6.setEnabled(false);
        errorLabel6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel6PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        errorLabel2.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        errorLabel2.setText("Formato no válido");
        errorLabel2.setEnabled(false);
        errorLabel2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel2PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        requirementsLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        requirementsLabel.setForeground(new java.awt.Color(102, 102, 102));
        requirementsLabel.setText("Al menos una mayúscula, minúcula, números y de longitud 8");
        jPanel1.add(requirementsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        dayTextField.setBackground(new java.awt.Color(255, 236, 217));
        dayTextField.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        dayTextField.setToolTipText("");
        dayTextField.setBorder(null);
        dayTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dayTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dayTextFieldMousePressed(evt);
            }
        });
        dayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(dayTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 91, 27));

        yearTextField.setBackground(new java.awt.Color(255, 236, 217));
        yearTextField.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        yearTextField.setToolTipText("");
        yearTextField.setBorder(null);
        yearTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        yearTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                yearTextFieldMousePressed(evt);
            }
        });
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(yearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 91, 27));

        cvvTextField.setBackground(new java.awt.Color(255, 236, 217));
        cvvTextField.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        cvvTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cvvTextField.setToolTipText("");
        cvvTextField.setBorder(null);
        cvvTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cvvTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cvvTextFieldMousePressed(evt);
            }
        });
        cvvTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(cvvTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 91, 27));

        CCTextField.setBackground(new java.awt.Color(255, 236, 217));
        CCTextField.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        CCTextField.setToolTipText("");
        CCTextField.setBorder(null);
        CCTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CCTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CCTextFieldMousePressed(evt);
            }
        });
        CCTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(CCTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 418, 27));

        monthLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        monthLabel.setForeground(new java.awt.Color(102, 102, 102));
        monthLabel.setText("MES:");
        jPanel1.add(monthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        yearLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(102, 102, 102));
        yearLabel.setText("AÑO:");
        jPanel1.add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, -1, -1));

        cvvLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        cvvLabel.setText("CVV:");
        jPanel1.add(cvvLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        emailLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        emailLabel.setText("CORREO ELECTRÓNICO*");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        monthTextField.setBackground(new java.awt.Color(255, 236, 217));
        monthTextField.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        monthTextField.setToolTipText("");
        monthTextField.setBorder(null);
        monthTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        monthTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                monthTextFieldMousePressed(evt);
            }
        });
        monthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(monthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 91, 27));

        statementLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        statementLabel.setForeground(new java.awt.Color(102, 102, 102));
        statementLabel.setText("Introduzca la fecha de caducidad y el CVV");
        jPanel1.add(statementLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, -1, -1));

        userExiste.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        userExiste.setForeground(new java.awt.Color(0, 153, 0));
        userExiste.setText("Ya existe una cuenta asociada a este correo. Por favor inicie sesión.");
        jPanel1.add(userExiste, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, -1, -1));

        userLabel1.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        userLabel1.setText("NOMBRE COMPLETO*");
        jPanel1.add(userLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 22));

        userTextField1.setBackground(new java.awt.Color(255, 236, 217));
        userTextField1.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        userTextField1.setToolTipText("");
        userTextField1.setBorder(null);
        userTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTextField1MousePressed(evt);
            }
        });
        userTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(userTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 418, 27));

        errorLabel4.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 12)); // NOI18N
        errorLabel4.setText("Formato no válido");
        errorLabel4.setEnabled(false);
        errorLabel4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel4PropertyChange(evt);
            }
        });
        jPanel1.add(errorLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 90, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 420, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 420, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 420, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 420, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 420, 20));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 420, 20));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 420, 20));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 90, 20));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 90, 20));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 90, 20));

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createaccLabel.setBackground(new java.awt.Color(255, 90, 95));
        createaccLabel.setFont(new java.awt.Font("Noto Sans SemiBold", 0, 48)); // NOI18N
        createaccLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createaccLabel.setText("REGISTRO");
        jPanel2.add(createaccLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/logopeque.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 90));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void promocodeTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promocodeTextFieldMousePressed

    }//GEN-LAST:event_promocodeTextFieldMousePressed

    private void promocodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promocodeTextFieldActionPerformed

    }//GEN-LAST:event_promocodeTextFieldActionPerformed

    private void passwordTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTextFieldMousePressed

    }//GEN-LAST:event_passwordTextFieldMousePressed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed

        // Inicializa los atributos con los valores de los campos de entrada del formulario
        String nombre = userTextField1.getText();
        String dni = DNITextField.getText();
        String correo = emailTextField.getText();
        char[] passwCharArray = passwordTextField.getPassword();
        String passw = new String(passwCharArray);
        String telefono = tlfTextField.getText();
        String numtarjeta = CCTextField.getText();
        String cvv = cvvTextField.getText();
        String promocode = promocodeTextField.getText();
        double saldo = 1000; // El saldo inicial de todos los clientes será de 1000
        boolean valido = true;
        userExiste.setVisible(false);
        int dia = -1;
        int mes = -1;
        int año = -1;

// Verifica la validez del nombre
        if (!Validate.validarNombre(nombre)) {
            errorLabel4.setVisible(true);
            valido = false;
            promocodeTextField.setText("");
        } else {
            errorLabel4.setVisible(false);
        }

// Verifica la validez del DNI
        if (!Validate.validarDNI(dni)) {
            errorLabel2.setVisible(true);
            valido = false;
            DNITextField.setText("");
        } else {
            errorLabel2.setVisible(false);
        }

// Verifica la validez del correo electrónico
        if (!Validate.validarEmail(correo)) {
            errorLabel6.setVisible(true);
            valido = false;
            emailTextField.setText("");
        } else {
            errorLabel6.setVisible(false);
        }

// Verifica la validez del número de teléfono
        if (!Validate.validarTelefono(telefono)) {
            errorLabel5.setVisible(true);
            valido = false;
            tlfTextField.setText("");
        } else {
            errorLabel5.setVisible(false);
        }

// Verifica la validez de la contraseña
        if (!Validate.validarContraseña(passw)) {
            errorLabel3.setVisible(true);
            requirementsLabel.setVisible(true);
            passwordTextField.setText("");
            valido = false;
        } else {
            errorLabel3.setVisible(false);
        }

// Obtiene la opción seleccionada en el ComboBox
        String selectedOption = (String) selectComboBox.getSelectedItem();
// Comprueba si el usuario ya existe en la base de datos
        boolean usuarioExiste = Validate.comprobarExistenciaCliente(correo.toLowerCase(), dni, telefono);

        if (selectedOption.equals("Seleccione entre:")) {
            noselectLabel.setVisible(true);
            userExiste.setVisible(false);
        } else if (usuarioExiste) {
            userExiste.setVisible(true);
            noselectLabel.setVisible(false);
        } else if (selectedOption.equals("Anfitrion") && valido) {
            // Registra un nuevo anfitrión si los datos son válidos y la opción seleccionada es "Anfitrion"
            noselectLabel.setVisible(false);
            Host nuevoAnfitrion = new Host(dni, nombre, correo.toLowerCase(), passw, telefono);
            Inicio.registrarCliente(nuevoAnfitrion);
            reseteoTexto();
            Aplicacion.cargaPantallaPrincipal();
        } else if (selectedOption.equals("Anfitrion") && !valido) {
            noselectLabel.setVisible(true);
        } else if (selectedOption.equals("Particular")) {
            // Comprueba si la opción seleccionada es "Particular"
            try {
                // Convierte los campos de fecha en números enteros
                if (!monthTextField.getText().isEmpty()) {
                    mes = Integer.parseInt(monthTextField.getText());
                } else {
                    System.err.println("El campo de día está vacío.");
                }

                if (!dayTextField.getText().isEmpty()) {
                    dia = Integer.parseInt(dayTextField.getText());
                } else {
                    System.err.println("El campo de mes está vacío.");
                }

                if (!yearTextField.getText().isEmpty()) {
                    año = Integer.parseInt(yearTextField.getText());
                } else {
                    System.err.println("El campo de año está vacío.");
                }
            } catch (NumberFormatException e) {
                System.err.println("Error al convertir el texto a número.");
                dia = -1;
                mes = -1;
                año = -1;
            }

            // Verifica la validez de la tarjeta de crédito
            if (!Validate.validarTarjeta(numtarjeta, dia, mes, año, cvv)) {
                errorLabel1.setVisible(true);
                valido = false;
                monthTextField.setText("");
                dayTextField.setText("");
                yearTextField.setText("");
                cvvTextField.setText("");
            } else {
                errorLabel1.setVisible(false);
            }

            // Verifica la validez del código promocional
            if (!Validate.validarPromocode(promocode)) {
                errorLabel8.setVisible(true);
                promocodeTextField.setText("");
                valido = false;
            } else {
                errorLabel8.setVisible(false);
            }

            if (valido) {
                // Si todos los datos son válidos, registra un nuevo cliente particular
                noselectLabel.setVisible(false);
                boolean vip = Validate.validarVipPromocode(promocode);
                LocalDate fechaCaducidad = LocalDate.of(año, mes, dia);
                Credito tarjeta = new Credito(nombre, numtarjeta, dia, mes, año, fechaCaducidad, cvv, saldo);
                Particular nuevoParticular = new Particular(tarjeta, vip, dni, nombre, correo.toLowerCase(), passw, telefono);
                Inicio.registrarCliente(nuevoParticular);
                reseteoTexto();
                Aplicacion.cargaPantallaPrincipal();
                return;
            }
            noselectLabel.setVisible(true);
        }


    }//GEN-LAST:event_registerButtonActionPerformed

    private void selectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectComboBoxActionPerformed
        // Obtiene la opción seleccionada en el ComboBox
        String selectedOption = (String) selectComboBox.getSelectedItem();

// Verifica si la opción seleccionada es "Particular"
        if (selectedOption.equals("Particular")) {
            // Si es "Particular", muestra los campos de entrada relevantes y las etiquetas asociadas
            monthTextField.setVisible(true);
            dayLabel.setVisible(true);
            dayTextField.setVisible(true);
            monthLabel.setVisible(true);
            yearTextField.setVisible(true);
            yearLabel.setVisible(true);
            cvvTextField.setVisible(true);
            cvvLabel.setVisible(true);
            promocodeTextField.setVisible(true);
            promocodeLabel.setVisible(true);

            CCTextField.setVisible(true);
            CCLabel.setVisible(true);

            // Muestra la etiqueta "Seleccione entre" para indicar que aún no se ha seleccionado ninguna opción
            noselectLabel.setVisible(true);

            // Muestra una etiqueta informativa
            statementLabel.setVisible(true);

            // Oculta la etiqueta de error "Seleccione entre" ya que ahora se ha seleccionado una opción
            noselectLabel.setVisible(false);

        } else {
            // Si la opción seleccionada no es "Particular", oculta los campos de entrada y las etiquetas asociadas
            monthTextField.setVisible(false);
            dayLabel.setVisible(false);
            dayTextField.setVisible(false);
            monthLabel.setVisible(false);
            yearTextField.setVisible(false);
            yearLabel.setVisible(false);
            cvvTextField.setVisible(false);
            cvvLabel.setVisible(false);
            promocodeTextField.setVisible(false);
            promocodeLabel.setVisible(false);

            CCTextField.setVisible(false);
            CCLabel.setVisible(false);

            // Oculta la etiqueta "Seleccione entre" ya que no es necesario
            noselectLabel.setVisible(false);

            // Oculta cualquier etiqueta de error que pueda estar visible
            errorLabel.setVisible(false);
            errorLabel1.setVisible(false);
            errorLabel2.setVisible(false);
            errorLabel6.setVisible(false);
            errorLabel3.setVisible(false);
            errorLabel8.setVisible(false);
            errorLabel5.setVisible(false);
            errorLabel4.setVisible(false);

            // Oculta la etiqueta informativa
            statementLabel.setVisible(false);
        }

    }//GEN-LAST:event_selectComboBoxActionPerformed

    private void existaccLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_existaccLabelMouseClicked
        reseteoTexto();
        Aplicacion.cardLayout.show(Aplicacion.cards, "Pantalla login");
    }//GEN-LAST:event_existaccLabelMouseClicked

    private void DNITextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNITextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNITextFieldMousePressed

    private void DNITextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNITextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNITextFieldActionPerformed

    private void emailTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldMousePressed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void tlfTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlfTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlfTextFieldMousePressed

    private void tlfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlfTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlfTextFieldActionPerformed

    private void errorLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabelPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabelPropertyChange

    private void errorLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel1PropertyChange

    private void errorLabel3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel3PropertyChange

    private void errorLabel8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel8PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel8PropertyChange

    private void errorLabel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel5PropertyChange

    private void errorLabel6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel6PropertyChange

    private void errorLabel2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel2PropertyChange

    private void dayTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dayTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextFieldMousePressed

    private void dayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextFieldActionPerformed

    private void yearTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldMousePressed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void cvvTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvvTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldMousePressed

    private void cvvTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldActionPerformed

    private void CCTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCTextFieldMousePressed

    private void CCTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCTextFieldActionPerformed

    private void monthTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldMousePressed

    private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldActionPerformed

    private void userTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextField1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextField1MousePressed

    private void userTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextField1ActionPerformed

    private void errorLabel4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel4PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel4PropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCLabel;
    private javax.swing.JTextField CCTextField;
    private javax.swing.JLabel DNILabel;
    private javax.swing.JTextField DNITextField;
    private javax.swing.JLabel createaccLabel;
    private javax.swing.JLabel cvvLabel;
    private javax.swing.JTextField cvvTextField;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel errorLabel1;
    private javax.swing.JLabel errorLabel2;
    private javax.swing.JLabel errorLabel3;
    private javax.swing.JLabel errorLabel4;
    private javax.swing.JLabel errorLabel5;
    private javax.swing.JLabel errorLabel6;
    private javax.swing.JLabel errorLabel8;
    private javax.swing.JLabel existaccLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel noselectLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel promocodeLabel;
    private javax.swing.JTextField promocodeTextField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel requirementsLabel;
    private javax.swing.JComboBox<String> selectComboBox;
    private javax.swing.JLabel statementLabel;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel tlfLabel;
    private javax.swing.JTextField tlfTextField;
    private javax.swing.JLabel userExiste;
    private javax.swing.JLabel userLabel1;
    private javax.swing.JTextField userTextField1;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
